lsi: false
safe: true
source: https://github.com/widiarrohman1234/widiarrohman1234.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge